### ISSUE TITLE
Scrollbars appear when grading code on Windows

### ISSUE THREAD

**Issue by ishantheperson** [diderot-edu/diderot-feedback#67] opened 2020-09-20 05:09 UTC
Each line of code has its own scrollbar which is quite distracting when trying to grade code for cost bounds.

It seems to happen because `.code-viewer code` has `overflow: scroll` set when it should be just `overflow-x: auto` (better yet: supply 1 scrollbar for the entire code viewer) 

![image](https://user-images.githubusercontent.com/1707565/93694801-d9a19200-fac4-11ea-88d1-3616aff8e8f6.png)

**Comment by umutacar** [comment] 2020-09-21 12:51
Hopefully fixed.  We don't have access to windows+edge unfortunately

**Comment by ishantheperson** [comment] 2020-09-21 14:57
You can use Virtual Andrew to get access to windows (this happened across all browsers) 

https://www.cmu.edu/computing/services/endpoint/software/virtual-andrew.html

**Comment by ishantheperson** [comment] 2020-09-24 04:13
Unfortunately doesn't appear to be resolved:
![image](https://user-images.githubusercontent.com/1707565/94100122-a0796280-fde1-11ea-8bf0-51251b45175a.png)

**Comment by kopecs** [comment] 2020-09-28 04:56
This is also reproducible on Linux (tested with firefox 81). It looks like `.submission-details code` has `overflow: scroll`; changing to `auto` removes the scrollbars.

**Comment by umutacar** [comment] 2020-10-01 11:37
should be fixed.

**Closed by umutacar** 2020-10-01 11:37 UTC
